name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: zip
      run: zip -r CPTH-${{ steps.get_version.outputs.VERSION }}.zip headers
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        files: CPTH-${{ steps.get_version.outputs.VERSION }}.zip
        name: CPTH ${{ steps.get_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
