name: "Release checksums"

on:
  release:
    types:
      - published

jobs:
  checksums:
    name: "Release checksums"
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Download assets and generate checksums
      run: |
        mkdir -p downloads
        cd downloads
        wget -c https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/CPTH-${{ steps.get_version.outputs.VERSION }}.zip
        wget -c https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/CPTH-${{ steps.get_version.outputs.VERSION }}-minified.zip
        shasum -a 256 *.* > CPTH-${{ steps.get_version.outputs.VERSION }}-checksums.txt

    - name: Upload checksums
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: CP Editor ${{ steps.get_version.outputs.VERSION }}
        files: downloads/CPTH-${{ steps.get_version.outputs.VERSION }}-checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
